export const BOARD_CONFIG = {
  background: {
    title: "사업배경",
    parentTitle: "사업개요",
    description: "병원자료 기반 의약품 안전관리 사업을 소개합니다.",
    writable: true,
    showKrdsNotice: false,
    bbsId: "",
  },
  objective: {
    title: "사업목적",
    parentTitle: "사업개요",
    description: "병원자료 기반 의약품 안전관리 사업의 목적을 알려드립니다.",
    writable: true,
    showKrdsNotice: false,
    bbsId: "",
  },
  coordinationCenter: {
    title: "협연센터",
    parentTitle: "사업개요",
    description: "협연센터로서 한국의약품안전관리원의 역할을 알려드립니다.",
    writable: true,
    showKrdsNotice: false,
    bbsId: "",
  },
  partnerInstitution: {
    title: "협력기관",
    parentTitle: "사업개요",
    description: "병원자료 기반 의약품 안전관리 사업의 협력기관입니다.",
    writable: true,
    showKrdsNotice: false,
    bbsId: "",
  },
  cdmDefinition: {
    title: "CDM 정의",
    parentTitle: "CDM이란",
    description: "병원자료 기반 CDM을 소개합니다.",
    writable: true,
    showKrdsNotice: false,
    bbsId: "",
  },
  cdmStructure: {
    title: "CDM 구조",
    parentTitle: "CDM이란",
    description: "CDM 데이터베이스가 포함하고 있는 정보를 알려드립니다.",
    writable: true,
    showKrdsNotice: false,
    bbsId: "",
  },
  cdmImplementation: {
    title: "CDM 구축과정",
    parentTitle: "CDM이란",
    description: "CDM 데이터베이스를 구축하는 과정을 알려드립니다.",
    writable: true,
    showKrdsNotice: false,
    bbsId: "",
  },
  cdmOverview: {
    title: "CDM 통합정보",
    parentTitle: "구축·분석",
    description: "구축정보, 분석정보, 정보마당의 통합게시판 입니다.",
    writable: true,
    showKrdsNotice: true,
    bbsId: "CDM0000008",
  },
  informationSecurity: {
    title: "정보보안",
    parentTitle: "CDM이란",
    description: "CDM 네트워크의 개인정보보호 및 정보보안 방법을 알려드립니다.",
    writable: true,
    showKrdsNotice: false,
    bbsId: "",
  },
  buildInfo: {
    title: "구축정보",
    parentTitle: "구축·분석",
    description: "병원자료를 CDM으로 변환할 때 필요한 도구 및 관련 자료를 알려드립니다.",
    writable: true,
    showKrdsNotice: false,
    bbsId: "",
  },
  analysisInfo: {
    title: "분석정보",
    parentTitle: "구축·분석",
    description: "CDM을 이용하여 의약품 안전성 분석 연구를 수행할 때 필요한 정보입니다.",
    writable: true,
    showKrdsNotice: false,
    bbsId: "",
  },
  notice: {
    title: "공지사항",
    parentTitle: "참여마당",
    description: "병원자료 기반 의약품 안전관리 사업 관련 공고나 행사 등을 알려드립니다.",
    writable: true,
    showKrdsNotice: false,
    bbsId: "CDM0000001",
  },
  pressRelease: {
    title: "보도자료",
    parentTitle: "참여마당",
    description: "병원자료 기반 의약품 안전관리 사업 관련 보도자료 모음 게시판입니다.",
    writable: true,
    showKrdsNotice: false,
    bbsId: "CDM0000002",
  },
  info: {
    title: "정보마당",
    parentTitle: "정보마당",
    description: "CDM을 이용하여 도출한 분석결과와 의약품 안전성 정보, 병원자료 기반 의약품 안전관리사업 관련 자료 등을 공개합니다.",
    writable: true,
    showKrdsNotice: true,
    bbsId: "CDM0000003",
  },
  meetingEventInfo: {
    title: "회의/행사 정보",
    description: "회의/행사 정보 입니다.",
    writable: true,
    showKrdsNotice: false,
    bbsId: "CDM0000004",
  },
  resourceCenter: {
    title: "자료실",
    description: "자료실 입니다.",
    writable: true,
    showKrdsNotice: false,
    bbsId: "CDM0000005",
  },
  researchProject: {
    title: "연구과제",
    description: "연구과제 입니다.",
    writable: true,
    showKrdsNotice: false,
    bbsId: "",
  },
  freeboard: {
    title: "자유게시판",
    description: "자유게시판 입니다.",
    writable: true,
    showKrdsNotice: false,
    bbsId: "CDM0000007",
  },
  qna: {
    title: "Q&A",
    description: "Q&A 입니다.",
    writable: true,
    showKrdsNotice: false,
    bbsId: "",
  },
} as const;

export type BoardType = keyof typeof BOARD_CONFIG;